<?php



/**
 * This class defines the structure of the 'sf_nested_comment' table.
 *
 *
 * This class was autogenerated by Propel 1.5.5 on:
 *
 * Wed 12 Jan 2011 09:38:09 PM WIT
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.plugins.sfNestedCommentPlugin.lib.model.map
 */
class sfNestedCommentTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.sfNestedCommentPlugin.lib.model.map.sfNestedCommentTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('sf_nested_comment');
		$this->setPhpName('sfNestedComment');
		$this->setClassname('sfNestedComment');
		$this->setPackage('plugins.sfNestedCommentPlugin.lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('AUTHOR_NAME', 'AuthorName', 'VARCHAR', false, 255, null);
		$this->addColumn('AUTHOR_EMAIL', 'AuthorEmail', 'VARCHAR', false, 255, null);
		$this->addColumn('AUTHOR_URL', 'AuthorUrl', 'VARCHAR', false, 255, null);
		$this->addColumn('CONTENT', 'Content', 'LONGVARCHAR', false, null, null);
		$this->addColumn('IS_MODERATED', 'IsModerated', 'BOOLEAN', false, null, false);
		$this->addColumn('COMMENTABLE_MODEL', 'CommentableModel', 'VARCHAR', false, 30, null);
		$this->addColumn('COMMENTABLE_ID', 'CommentableId', 'INTEGER', false, null, null);
		$this->addColumn('USER_ID', 'UserId', 'INTEGER', false, null, null);
		$this->addForeignKey('SF_COMMENT_ID', 'SfCommentId', 'INTEGER', 'sf_nested_comment', 'ID', false, null, null);
		$this->addColumn('EXTRA', 'Extra', 'VARCHAR', true, 255, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('TREE_LEFT', 'TreeLeft', 'INTEGER', false, null, null);
		$this->addColumn('TREE_RIGHT', 'TreeRight', 'INTEGER', false, null, null);
		$this->addColumn('TREE_LEVEL', 'TreeLevel', 'INTEGER', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('sfNestedCommentRelatedBySfCommentId', 'sfNestedComment', RelationMap::MANY_TO_ONE, array('sf_comment_id' => 'id', ), 'CASCADE', null);
    $this->addRelation('sfNestedCommentRelatedById', 'sfNestedComment', RelationMap::ONE_TO_MANY, array('id' => 'sf_comment_id', ), 'CASCADE', null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'nested_set' => array('left_column' => 'tree_left', 'right_column' => 'tree_right', 'level_column' => 'tree_level', 'use_scope' => 'true', 'scope_column' => 'extra', 'method_proxies' => 'false', ),
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // sfNestedCommentTableMap
