<?php


/**
 * Base static class for performing query and update operations on the 'sf_nested_comment' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.5 on:
 *
 * Wed 12 Jan 2011 09:38:09 PM WIT
 *
 * @package    propel.generator.plugins.sfNestedCommentPlugin.lib.model.om
 */
abstract class BasesfNestedCommentPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'sf_nested_comment';

	/** the related Propel class for this table */
	const OM_CLASS = 'sfNestedComment';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'plugins.sfNestedCommentPlugin.lib.model.sfNestedComment';

	/** the related TableMap class for this table */
	const TM_CLASS = 'sfNestedCommentTableMap';
	
	/** The total number of columns. */
	const NUM_COLUMNS = 16;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ID field */
	const ID = 'sf_nested_comment.ID';

	/** the column name for the AUTHOR_NAME field */
	const AUTHOR_NAME = 'sf_nested_comment.AUTHOR_NAME';

	/** the column name for the AUTHOR_EMAIL field */
	const AUTHOR_EMAIL = 'sf_nested_comment.AUTHOR_EMAIL';

	/** the column name for the AUTHOR_URL field */
	const AUTHOR_URL = 'sf_nested_comment.AUTHOR_URL';

	/** the column name for the CONTENT field */
	const CONTENT = 'sf_nested_comment.CONTENT';

	/** the column name for the IS_MODERATED field */
	const IS_MODERATED = 'sf_nested_comment.IS_MODERATED';

	/** the column name for the COMMENTABLE_MODEL field */
	const COMMENTABLE_MODEL = 'sf_nested_comment.COMMENTABLE_MODEL';

	/** the column name for the COMMENTABLE_ID field */
	const COMMENTABLE_ID = 'sf_nested_comment.COMMENTABLE_ID';

	/** the column name for the USER_ID field */
	const USER_ID = 'sf_nested_comment.USER_ID';

	/** the column name for the SF_COMMENT_ID field */
	const SF_COMMENT_ID = 'sf_nested_comment.SF_COMMENT_ID';

	/** the column name for the EXTRA field */
	const EXTRA = 'sf_nested_comment.EXTRA';

	/** the column name for the CREATED_AT field */
	const CREATED_AT = 'sf_nested_comment.CREATED_AT';

	/** the column name for the UPDATED_AT field */
	const UPDATED_AT = 'sf_nested_comment.UPDATED_AT';

	/** the column name for the TREE_LEFT field */
	const TREE_LEFT = 'sf_nested_comment.TREE_LEFT';

	/** the column name for the TREE_RIGHT field */
	const TREE_RIGHT = 'sf_nested_comment.TREE_RIGHT';

	/** the column name for the TREE_LEVEL field */
	const TREE_LEVEL = 'sf_nested_comment.TREE_LEVEL';

	/**
	 * An identiy map to hold any loaded instances of sfNestedComment objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array sfNestedComment[]
	 */
	public static $instances = array();


	// nested_set behavior
	
	/**
	 * Left column for the set
	 */
	const LEFT_COL = 'sf_nested_comment.TREE_LEFT';
	
	/**
	 * Right column for the set
	 */
	const RIGHT_COL = 'sf_nested_comment.TREE_RIGHT';
	
	/**
	 * Level column for the set
	 */
	const LEVEL_COL = 'sf_nested_comment.TREE_LEVEL';
	
	/**
	 * Scope column for the set
	 */
	const SCOPE_COL = 'sf_nested_comment.EXTRA';

	// symfony behavior
	
	/**
	 * Indicates whether the current model includes I18N.
	 */
	const IS_I18N = false;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Id', 'AuthorName', 'AuthorEmail', 'AuthorUrl', 'Content', 'IsModerated', 'CommentableModel', 'CommentableId', 'UserId', 'SfCommentId', 'Extra', 'CreatedAt', 'UpdatedAt', 'TreeLeft', 'TreeRight', 'TreeLevel', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'authorName', 'authorEmail', 'authorUrl', 'content', 'isModerated', 'commentableModel', 'commentableId', 'userId', 'sfCommentId', 'extra', 'createdAt', 'updatedAt', 'treeLeft', 'treeRight', 'treeLevel', ),
		BasePeer::TYPE_COLNAME => array (self::ID, self::AUTHOR_NAME, self::AUTHOR_EMAIL, self::AUTHOR_URL, self::CONTENT, self::IS_MODERATED, self::COMMENTABLE_MODEL, self::COMMENTABLE_ID, self::USER_ID, self::SF_COMMENT_ID, self::EXTRA, self::CREATED_AT, self::UPDATED_AT, self::TREE_LEFT, self::TREE_RIGHT, self::TREE_LEVEL, ),
		BasePeer::TYPE_RAW_COLNAME => array ('ID', 'AUTHOR_NAME', 'AUTHOR_EMAIL', 'AUTHOR_URL', 'CONTENT', 'IS_MODERATED', 'COMMENTABLE_MODEL', 'COMMENTABLE_ID', 'USER_ID', 'SF_COMMENT_ID', 'EXTRA', 'CREATED_AT', 'UPDATED_AT', 'TREE_LEFT', 'TREE_RIGHT', 'TREE_LEVEL', ),
		BasePeer::TYPE_FIELDNAME => array ('id', 'author_name', 'author_email', 'author_url', 'content', 'is_moderated', 'commentable_model', 'commentable_id', 'user_id', 'sf_comment_id', 'extra', 'created_at', 'updated_at', 'tree_left', 'tree_right', 'tree_level', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'AuthorName' => 1, 'AuthorEmail' => 2, 'AuthorUrl' => 3, 'Content' => 4, 'IsModerated' => 5, 'CommentableModel' => 6, 'CommentableId' => 7, 'UserId' => 8, 'SfCommentId' => 9, 'Extra' => 10, 'CreatedAt' => 11, 'UpdatedAt' => 12, 'TreeLeft' => 13, 'TreeRight' => 14, 'TreeLevel' => 15, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'authorName' => 1, 'authorEmail' => 2, 'authorUrl' => 3, 'content' => 4, 'isModerated' => 5, 'commentableModel' => 6, 'commentableId' => 7, 'userId' => 8, 'sfCommentId' => 9, 'extra' => 10, 'createdAt' => 11, 'updatedAt' => 12, 'treeLeft' => 13, 'treeRight' => 14, 'treeLevel' => 15, ),
		BasePeer::TYPE_COLNAME => array (self::ID => 0, self::AUTHOR_NAME => 1, self::AUTHOR_EMAIL => 2, self::AUTHOR_URL => 3, self::CONTENT => 4, self::IS_MODERATED => 5, self::COMMENTABLE_MODEL => 6, self::COMMENTABLE_ID => 7, self::USER_ID => 8, self::SF_COMMENT_ID => 9, self::EXTRA => 10, self::CREATED_AT => 11, self::UPDATED_AT => 12, self::TREE_LEFT => 13, self::TREE_RIGHT => 14, self::TREE_LEVEL => 15, ),
		BasePeer::TYPE_RAW_COLNAME => array ('ID' => 0, 'AUTHOR_NAME' => 1, 'AUTHOR_EMAIL' => 2, 'AUTHOR_URL' => 3, 'CONTENT' => 4, 'IS_MODERATED' => 5, 'COMMENTABLE_MODEL' => 6, 'COMMENTABLE_ID' => 7, 'USER_ID' => 8, 'SF_COMMENT_ID' => 9, 'EXTRA' => 10, 'CREATED_AT' => 11, 'UPDATED_AT' => 12, 'TREE_LEFT' => 13, 'TREE_RIGHT' => 14, 'TREE_LEVEL' => 15, ),
		BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'author_name' => 1, 'author_email' => 2, 'author_url' => 3, 'content' => 4, 'is_moderated' => 5, 'commentable_model' => 6, 'commentable_id' => 7, 'user_id' => 8, 'sf_comment_id' => 9, 'extra' => 10, 'created_at' => 11, 'updated_at' => 12, 'tree_left' => 13, 'tree_right' => 14, 'tree_level' => 15, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, )
	);

	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. sfNestedCommentPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(sfNestedCommentPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      Criteria $criteria object containing the columns to add.
	 * @param      string   $alias    optional table alias
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria, $alias = null)
	{
		if (null === $alias) {
			$criteria->addSelectColumn(sfNestedCommentPeer::ID);
			$criteria->addSelectColumn(sfNestedCommentPeer::AUTHOR_NAME);
			$criteria->addSelectColumn(sfNestedCommentPeer::AUTHOR_EMAIL);
			$criteria->addSelectColumn(sfNestedCommentPeer::AUTHOR_URL);
			$criteria->addSelectColumn(sfNestedCommentPeer::CONTENT);
			$criteria->addSelectColumn(sfNestedCommentPeer::IS_MODERATED);
			$criteria->addSelectColumn(sfNestedCommentPeer::COMMENTABLE_MODEL);
			$criteria->addSelectColumn(sfNestedCommentPeer::COMMENTABLE_ID);
			$criteria->addSelectColumn(sfNestedCommentPeer::USER_ID);
			$criteria->addSelectColumn(sfNestedCommentPeer::SF_COMMENT_ID);
			$criteria->addSelectColumn(sfNestedCommentPeer::EXTRA);
			$criteria->addSelectColumn(sfNestedCommentPeer::CREATED_AT);
			$criteria->addSelectColumn(sfNestedCommentPeer::UPDATED_AT);
			$criteria->addSelectColumn(sfNestedCommentPeer::TREE_LEFT);
			$criteria->addSelectColumn(sfNestedCommentPeer::TREE_RIGHT);
			$criteria->addSelectColumn(sfNestedCommentPeer::TREE_LEVEL);
		} else {
			$criteria->addSelectColumn($alias . '.ID');
			$criteria->addSelectColumn($alias . '.AUTHOR_NAME');
			$criteria->addSelectColumn($alias . '.AUTHOR_EMAIL');
			$criteria->addSelectColumn($alias . '.AUTHOR_URL');
			$criteria->addSelectColumn($alias . '.CONTENT');
			$criteria->addSelectColumn($alias . '.IS_MODERATED');
			$criteria->addSelectColumn($alias . '.COMMENTABLE_MODEL');
			$criteria->addSelectColumn($alias . '.COMMENTABLE_ID');
			$criteria->addSelectColumn($alias . '.USER_ID');
			$criteria->addSelectColumn($alias . '.SF_COMMENT_ID');
			$criteria->addSelectColumn($alias . '.EXTRA');
			$criteria->addSelectColumn($alias . '.CREATED_AT');
			$criteria->addSelectColumn($alias . '.UPDATED_AT');
			$criteria->addSelectColumn($alias . '.TREE_LEFT');
			$criteria->addSelectColumn($alias . '.TREE_RIGHT');
			$criteria->addSelectColumn($alias . '.TREE_LEVEL');
		}
	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(sfNestedCommentPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			sfNestedCommentPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(sfNestedCommentPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasesfNestedCommentPeer', $criteria, $con);
		}

		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     sfNestedComment
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = sfNestedCommentPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return sfNestedCommentPeer::populateObjects(sfNestedCommentPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(sfNestedCommentPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			sfNestedCommentPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasesfNestedCommentPeer', $criteria, $con);
		}


		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      sfNestedComment $value A sfNestedComment object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(sfNestedComment $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A sfNestedComment object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof sfNestedComment) {
				$key = (string) $value->getId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or sfNestedComment object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     sfNestedComment Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Method to invalidate the instance pool of all tables related to sf_nested_comment
	 * by a foreign key with ON DELETE CASCADE
	 */
	public static function clearRelatedInstancePool()
	{
		// Invalidate objects in sfNestedCommentPeer instance pool, 
		// since one or more of them may be deleted by ON DELETE CASCADE/SETNULL rule.
		sfNestedCommentPeer::clearInstancePool();
	}

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol] === null) {
			return null;
		}
		return (string) $row[$startcol];
	}

	/**
	 * Retrieves the primary key from the DB resultset row 
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, an array of the primary key columns will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     mixed The primary key of the row
	 */
	public static function getPrimaryKeyFromRow($row, $startcol = 0)
	{
		return (int) $row[$startcol];
	}
	
	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = sfNestedCommentPeer::getOMClass(false);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = sfNestedCommentPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = sfNestedCommentPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://www.propelorm.org/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				sfNestedCommentPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}
	/**
	 * Populates an object of the default type or an object that inherit from the default.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     array (sfNestedComment object, last column rank)
	 */
	public static function populateObject($row, $startcol = 0)
	{
		$key = sfNestedCommentPeer::getPrimaryKeyHashFromRow($row, $startcol);
		if (null !== ($obj = sfNestedCommentPeer::getInstanceFromPool($key))) {
			// We no longer rehydrate the object, since this can cause data loss.
			// See http://www.propelorm.org/ticket/509
			// $obj->hydrate($row, $startcol, true); // rehydrate
			$col = $startcol + sfNestedCommentPeer::NUM_COLUMNS;
		} else {
			$cls = sfNestedCommentPeer::OM_CLASS;
			$obj = new $cls();
			$col = $obj->hydrate($row, $startcol);
			sfNestedCommentPeer::addInstanceToPool($obj, $key);
		}
		return array($obj, $col);
	}

	/**
	 * Returns the number of rows matching criteria, joining all related tables
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAll(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(sfNestedCommentPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			sfNestedCommentPeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(sfNestedCommentPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasesfNestedCommentPeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}

	/**
	 * Selects a collection of sfNestedComment objects pre-filled with all related objects.
	 *
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of sfNestedComment objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAll(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		sfNestedCommentPeer::addSelectColumns($criteria);
		$startcol2 = (sfNestedCommentPeer::NUM_COLUMNS - sfNestedCommentPeer::NUM_LAZY_LOAD_COLUMNS);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasesfNestedCommentPeer', $criteria, $con);
		}

		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = sfNestedCommentPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = sfNestedCommentPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://www.propelorm.org/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$cls = sfNestedCommentPeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				sfNestedCommentPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}

	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * Add a TableMap instance to the database for this peer class.
	 */
	public static function buildTableMap()
	{
	  $dbMap = Propel::getDatabaseMap(BasesfNestedCommentPeer::DATABASE_NAME);
	  if (!$dbMap->hasTable(BasesfNestedCommentPeer::TABLE_NAME))
	  {
	    $dbMap->addTableObject(new sfNestedCommentTableMap());
	  }
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * If $withPrefix is true, the returned path
	 * uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @param      boolean $withPrefix Whether or not to return the path with the class name
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass($withPrefix = true)
	{
		return $withPrefix ? sfNestedCommentPeer::CLASS_DEFAULT : sfNestedCommentPeer::OM_CLASS;
	}

	/**
	 * Method perform an INSERT on the database, given a sfNestedComment or Criteria object.
	 *
	 * @param      mixed $values Criteria or sfNestedComment object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(sfNestedCommentPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from sfNestedComment object
		}

		if ($criteria->containsKey(sfNestedCommentPeer::ID) && $criteria->keyContainsValue(sfNestedCommentPeer::ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.sfNestedCommentPeer::ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

		return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a sfNestedComment or Criteria object.
	 *
	 * @param      mixed $values Criteria or sfNestedComment object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(sfNestedCommentPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(sfNestedCommentPeer::ID);
			$value = $criteria->remove(sfNestedCommentPeer::ID);
			if ($value) {
				$selectCriteria->add(sfNestedCommentPeer::ID, $value, $comparison);
			} else {
				$selectCriteria->setPrimaryTableName(sfNestedCommentPeer::TABLE_NAME);
			}

		} else { // $values is sfNestedComment object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		return BasePeer::doUpdate($selectCriteria, $criteria, $con);
	}

	/**
	 * Method to DELETE all rows from the sf_nested_comment table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(sfNestedCommentPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += sfNestedCommentPeer::doOnDeleteCascade(new Criteria(sfNestedCommentPeer::DATABASE_NAME), $con);
			$affectedRows += BasePeer::doDeleteAll(sfNestedCommentPeer::TABLE_NAME, $con, sfNestedCommentPeer::DATABASE_NAME);
			// Because this db requires some delete cascade/set null emulation, we have to
			// clear the cached instance *after* the emulation has happened (since
			// instances get re-added by the select statement contained therein).
			sfNestedCommentPeer::clearInstancePool();
			sfNestedCommentPeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a sfNestedComment or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or sfNestedComment object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(sfNestedCommentPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof sfNestedComment) { // it's a model object
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else { // it's a primary key, or an array of pks
			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(sfNestedCommentPeer::ID, (array) $values, Criteria::IN);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			// cloning the Criteria in case it's modified by doSelect() or doSelectStmt()
			$c = clone $criteria;
			$affectedRows += sfNestedCommentPeer::doOnDeleteCascade($c, $con);
			
			// Because this db requires some delete cascade/set null emulation, we have to
			// clear the cached instance *after* the emulation has happened (since
			// instances get re-added by the select statement contained therein).
			if ($values instanceof Criteria) {
				sfNestedCommentPeer::clearInstancePool();
			} elseif ($values instanceof sfNestedComment) { // it's a model object
				sfNestedCommentPeer::removeInstanceFromPool($values);
			} else { // it's a primary key, or an array of pks
				foreach ((array) $values as $singleval) {
					sfNestedCommentPeer::removeInstanceFromPool($singleval);
				}
			}
			
			$affectedRows += BasePeer::doDelete($criteria, $con);
			sfNestedCommentPeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * This is a method for emulating ON DELETE CASCADE for DBs that don't support this
	 * feature (like MySQL or SQLite).
	 *
	 * This method is not very speedy because it must perform a query first to get
	 * the implicated records and then perform the deletes by calling those Peer classes.
	 *
	 * This method should be used within a transaction if possible.
	 *
	 * @param      Criteria $criteria
	 * @param      PropelPDO $con
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	protected static function doOnDeleteCascade(Criteria $criteria, PropelPDO $con)
	{
		// initialize var to track total num of affected rows
		$affectedRows = 0;

		// first find the objects that are implicated by the $criteria
		$objects = sfNestedCommentPeer::doSelect($criteria, $con);
		foreach ($objects as $obj) {


			// delete related sfNestedComment objects
			$criteria = new Criteria(sfNestedCommentPeer::DATABASE_NAME);
			
			$criteria->add(sfNestedCommentPeer::SF_COMMENT_ID, $obj->getId());
			$affectedRows += sfNestedCommentPeer::doDelete($criteria, $con);
		}
		return $affectedRows;
	}

	/**
	 * Validates all modified columns of given sfNestedComment object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      sfNestedComment $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(sfNestedComment $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(sfNestedCommentPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(sfNestedCommentPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		return BasePeer::doValidate(sfNestedCommentPeer::DATABASE_NAME, sfNestedCommentPeer::TABLE_NAME, $columns);
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     sfNestedComment
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = sfNestedCommentPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(sfNestedCommentPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(sfNestedCommentPeer::DATABASE_NAME);
		$criteria->add(sfNestedCommentPeer::ID, $pk);

		$v = sfNestedCommentPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(sfNestedCommentPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(sfNestedCommentPeer::DATABASE_NAME);
			$criteria->add(sfNestedCommentPeer::ID, $pks, Criteria::IN);
			$objs = sfNestedCommentPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

	// nested_set behavior
	
	/**
	 * Returns the root nodes for the tree
	 *
	 * @param      PropelPDO $con	Connection to use.
	 * @return     sfNestedComment			Propel object for root node
	 */
	public static function retrieveRoots(Criteria $criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(sfNestedCommentPeer::DATABASE_NAME);
		}
		$criteria->add(sfNestedCommentPeer::LEFT_COL, 1, Criteria::EQUAL);
	
		return sfNestedCommentPeer::doSelect($criteria, $con);
	}
	
	/**
	 * Returns the root node for a given scope
	 *
	 * @param      int $scope		Scope to determine which root node to return
	 * @param      PropelPDO $con	Connection to use.
	 * @return     sfNestedComment			Propel object for root node
	 */
	public static function retrieveRoot($scope = null, PropelPDO $con = null)
	{
		$c = new Criteria(sfNestedCommentPeer::DATABASE_NAME);
		$c->add(sfNestedCommentPeer::LEFT_COL, 1, Criteria::EQUAL);
		$c->add(sfNestedCommentPeer::SCOPE_COL, $scope, Criteria::EQUAL);
	
		return sfNestedCommentPeer::doSelectOne($c, $con);
	}
	
	/**
	 * Returns the whole tree node for a given scope
	 *
	 * @param      int $scope		Scope to determine which root node to return
	 * @param      Criteria $criteria	Optional Criteria to filter the query
	 * @param      PropelPDO $con	Connection to use.
	 * @return     sfNestedComment			Propel object for root node
	 */
	public static function retrieveTree($scope = null, Criteria $criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(sfNestedCommentPeer::DATABASE_NAME);
		}
		$criteria->addAscendingOrderByColumn(sfNestedCommentPeer::LEFT_COL);
		$criteria->add(sfNestedCommentPeer::SCOPE_COL, $scope, Criteria::EQUAL);
		
		return sfNestedCommentPeer::doSelect($criteria, $con);
	}
	
	/**
	 * Tests if node is valid
	 *
	 * @param      sfNestedComment $node	Propel object for src node
	 * @return     bool
	 */
	public static function isValid(sfNestedComment $node = null)
	{
		if (is_object($node) && $node->getRightValue() > $node->getLeftValue()) {
			return true;
		} else {
			return false;
		}
	}
	
	/**
	 * Delete an entire tree
	 * 
	 * @param      int $scope		Scope to determine which tree to delete
	 * @param      PropelPDO $con	Connection to use.
	 *
	 * @return     int  The number of deleted nodes
	 */
	public static function deleteTree($scope = null, PropelPDO $con = null)
	{
		$c = new Criteria(sfNestedCommentPeer::DATABASE_NAME);
		$c->add(sfNestedCommentPeer::SCOPE_COL, $scope, Criteria::EQUAL);
		return sfNestedCommentPeer::doDelete($c, $con);
	}
	
	/**
	 * Adds $delta to all L and R values that are >= $first and <= $last.
	 * '$delta' can also be negative.
	 *
	 * @param      int $delta		Value to be shifted by, can be negative
	 * @param      int $first		First node to be shifted
	 * @param      int $last			Last node to be shifted (optional)
	 * @param      int $scope		Scope to use for the shift
	 * @param      PropelPDO $con		Connection to use.
	 */
	public static function shiftRLValues($delta, $first, $last = null, $scope = null, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(sfNestedCommentPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
	
		// Shift left column values
		$whereCriteria = new Criteria(sfNestedCommentPeer::DATABASE_NAME);
		$criterion = $whereCriteria->getNewCriterion(sfNestedCommentPeer::LEFT_COL, $first, Criteria::GREATER_EQUAL);
		if (null !== $last) {
			$criterion->addAnd($whereCriteria->getNewCriterion(sfNestedCommentPeer::LEFT_COL, $last, Criteria::LESS_EQUAL));
		}
		$whereCriteria->add($criterion);
		$whereCriteria->add(sfNestedCommentPeer::SCOPE_COL, $scope, Criteria::EQUAL);
		
		$valuesCriteria = new Criteria(sfNestedCommentPeer::DATABASE_NAME);
		$valuesCriteria->add(sfNestedCommentPeer::LEFT_COL, array('raw' => sfNestedCommentPeer::LEFT_COL . ' + ?', 'value' => $delta), Criteria::CUSTOM_EQUAL);
	
		BasePeer::doUpdate($whereCriteria, $valuesCriteria, $con);
	
		// Shift right column values
		$whereCriteria = new Criteria(sfNestedCommentPeer::DATABASE_NAME);
		$criterion = $whereCriteria->getNewCriterion(sfNestedCommentPeer::RIGHT_COL, $first, Criteria::GREATER_EQUAL);
		if (null !== $last) {
			$criterion->addAnd($whereCriteria->getNewCriterion(sfNestedCommentPeer::RIGHT_COL, $last, Criteria::LESS_EQUAL));
		}
		$whereCriteria->add($criterion);
		$whereCriteria->add(sfNestedCommentPeer::SCOPE_COL, $scope, Criteria::EQUAL);
	
		$valuesCriteria = new Criteria(sfNestedCommentPeer::DATABASE_NAME);
		$valuesCriteria->add(sfNestedCommentPeer::RIGHT_COL, array('raw' => sfNestedCommentPeer::RIGHT_COL . ' + ?', 'value' => $delta), Criteria::CUSTOM_EQUAL);
	
		BasePeer::doUpdate($whereCriteria, $valuesCriteria, $con);
	}
	
	/**
	 * Adds $delta to level for nodes having left value >= $first and right value <= $last.
	 * '$delta' can also be negative.
	 *
	 * @param      int $delta		Value to be shifted by, can be negative
	 * @param      int $first		First node to be shifted
	 * @param      int $last			Last node to be shifted
	 * @param      int $scope		Scope to use for the shift
	 * @param      PropelPDO $con		Connection to use.
	 */
	public static function shiftLevel($delta, $first, $last, $scope = null, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(sfNestedCommentPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
	
		$whereCriteria = new Criteria(sfNestedCommentPeer::DATABASE_NAME);
		$whereCriteria->add(sfNestedCommentPeer::LEFT_COL, $first, Criteria::GREATER_EQUAL);
		$whereCriteria->add(sfNestedCommentPeer::RIGHT_COL, $last, Criteria::LESS_EQUAL);
		$whereCriteria->add(sfNestedCommentPeer::SCOPE_COL, $scope, Criteria::EQUAL);
		
		$valuesCriteria = new Criteria(sfNestedCommentPeer::DATABASE_NAME);
		$valuesCriteria->add(sfNestedCommentPeer::LEVEL_COL, array('raw' => sfNestedCommentPeer::LEVEL_COL . ' + ?', 'value' => $delta), Criteria::CUSTOM_EQUAL);
	
		BasePeer::doUpdate($whereCriteria, $valuesCriteria, $con);
	}
	
	/**
	 * Reload all already loaded nodes to sync them with updated db
	 *
	 * @param      PropelPDO $con		Connection to use.
	 */
	public static function updateLoadedNodes(PropelPDO $con = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			$keys = array();
			foreach (sfNestedCommentPeer::$instances as $obj) {
				$keys[] = $obj->getPrimaryKey();
			}
	
			if (!empty($keys)) {
				// We don't need to alter the object instance pool; we're just modifying these ones
				// already in the pool.
				$criteria = new Criteria(sfNestedCommentPeer::DATABASE_NAME);
				$criteria->add(sfNestedCommentPeer::ID, $keys, Criteria::IN);
	
				$stmt = sfNestedCommentPeer::doSelectStmt($criteria, $con);
				while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
					$key = sfNestedCommentPeer::getPrimaryKeyHashFromRow($row, 0);
					if (null !== ($object = sfNestedCommentPeer::getInstanceFromPool($key))) {
						$object->setLeftValue($row[13]);
						$object->setRightValue($row[14]);
						$object->setLevel($row[15]);
						$object->clearNestedSetChildren();
					}
				}
				$stmt->closeCursor();
			}
		}
	}
	
	/**
	 * Update the tree to allow insertion of a leaf at the specified position
	 *
	 * @param      int $left	left column value
	 * @param      integer $scope	scope column value
	 * @param      PropelPDO $con	Connection to use.
	 */
	public static function makeRoomForLeaf($left, $scope, PropelPDO $con = null)
	{	
		// Update database nodes
		sfNestedCommentPeer::shiftRLValues(2, $left, null, $scope, $con);
	
		// Update all loaded nodes
		sfNestedCommentPeer::updateLoadedNodes($con);
	}
	
	/**
	 * Update the tree to allow insertion of a leaf at the specified position
	 *
	 * @param      integer $scope	scope column value
	 * @param      PropelPDO $con	Connection to use.
	 */
	public static function fixLevels($scope, PropelPDO $con = null)
	{
		$c = new Criteria();
		$c->add(sfNestedCommentPeer::SCOPE_COL, $scope, Criteria::EQUAL);
		$c->addAscendingOrderByColumn(sfNestedCommentPeer::LEFT_COL);
		$stmt = sfNestedCommentPeer::doSelectStmt($c, $con);
		
		// set the class once to avoid overhead in the loop
		$cls = sfNestedCommentPeer::getOMClass(false);
		$level = null;
		// iterate over the statement
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
	
			// hydrate object
			$key = sfNestedCommentPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null === ($obj = sfNestedCommentPeer::getInstanceFromPool($key))) {
				$obj = new $cls();
				$obj->hydrate($row);
				sfNestedCommentPeer::addInstanceToPool($obj, $key);
			}
			
			// compute level
			// Algorithm shamelessly stolen from sfPropelActAsNestedSetBehaviorPlugin
			// Probably authored by Tristan Rivoallan
			if ($level === null) {
				$level = 0;
				$i = 0;
				$prev = array($obj->getRightValue());
			} else {
				while ($obj->getRightValue() > $prev[$i]) {
					$i--;
				}
				$level = ++$i;
				$prev[$i] = $obj->getRightValue();
			}
			
			// update level in node if necessary
			if ($obj->getLevel() !== $level) {
				$obj->setLevel($level);
				$obj->save($con);
			}
		}
		$stmt->closeCursor();
	}

	// symfony behavior
	
	/**
	 * Returns an array of arrays that contain columns in each unique index.
	 *
	 * @return array
	 */
	static public function getUniqueColumnNames()
	{
	  return array();
	}

	// symfony_behaviors behavior
	
	/**
	 * Returns the name of the hook to call from inside the supplied method.
	 *
	 * @param string $method The calling method
	 *
	 * @return string A hook name for {@link sfMixer}
	 *
	 * @throws LogicException If the method name is not recognized
	 */
	static private function getMixerPreSelectHook($method)
	{
	  if (preg_match('/^do(Select|Count)(Join(All(Except)?)?|Stmt)?/', $method, $match))
	  {
	    return sprintf('BasesfNestedCommentPeer:%s:%1$s', 'Count' == $match[1] ? 'doCount' : $match[0]);
	  }
	
	  throw new LogicException(sprintf('Unrecognized function "%s"', $method));
	}

} // BasesfNestedCommentPeer

// This is the static code needed to register the TableMap for this table with the main Propel class.
//
BasesfNestedCommentPeer::buildTableMap();

