<?php


/**
 * Base class that represents a row from the 'sf_nested_comment' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.5 on:
 *
 * Wed 12 Jan 2011 09:38:09 PM WIT
 *
 * @package    propel.generator.plugins.sfNestedCommentPlugin.lib.model.om
 */
abstract class BasesfNestedComment extends BaseObject  implements Persistent
{

	/**
	 * Peer class name
	 */
	const PEER = 'sfNestedCommentPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        sfNestedCommentPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the author_name field.
	 * @var        string
	 */
	protected $author_name;

	/**
	 * The value for the author_email field.
	 * @var        string
	 */
	protected $author_email;

	/**
	 * The value for the author_url field.
	 * @var        string
	 */
	protected $author_url;

	/**
	 * The value for the content field.
	 * @var        string
	 */
	protected $content;

	/**
	 * The value for the is_moderated field.
	 * Note: this column has a database default value of: false
	 * @var        boolean
	 */
	protected $is_moderated;

	/**
	 * The value for the commentable_model field.
	 * @var        string
	 */
	protected $commentable_model;

	/**
	 * The value for the commentable_id field.
	 * @var        int
	 */
	protected $commentable_id;

	/**
	 * The value for the user_id field.
	 * @var        int
	 */
	protected $user_id;

	/**
	 * The value for the sf_comment_id field.
	 * @var        int
	 */
	protected $sf_comment_id;

	/**
	 * The value for the extra field.
	 * @var        string
	 */
	protected $extra;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * The value for the tree_left field.
	 * @var        int
	 */
	protected $tree_left;

	/**
	 * The value for the tree_right field.
	 * @var        int
	 */
	protected $tree_right;

	/**
	 * The value for the tree_level field.
	 * @var        int
	 */
	protected $tree_level;

	/**
	 * @var        sfNestedComment
	 */
	protected $asfNestedCommentRelatedBySfCommentId;

	/**
	 * @var        array sfNestedComment[] Collection to store aggregation of sfNestedComment objects.
	 */
	protected $collsfNestedCommentsRelatedById;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// nested_set behavior
	
	/**
	 * Queries to be executed in the save transaction
	 * @var        array
	 */
	protected $nestedSetQueries = array();
	
	/**
	 * Internal cache for children nodes
	 * @var        null|PropelObjectCollection
	 */
	protected $collNestedSetChildren = null;
	
	/**
	 * Internal cache for parent node
	 * @var        null|sfNestedComment
	 */
	protected $aNestedSetParent = null;
	

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->is_moderated = false;
	}

	/**
	 * Initializes internal state of BasesfNestedComment object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [author_name] column value.
	 * 
	 * @return     string
	 */
	public function getAuthorName()
	{
		return $this->author_name;
	}

	/**
	 * Get the [author_email] column value.
	 * 
	 * @return     string
	 */
	public function getAuthorEmail()
	{
		return $this->author_email;
	}

	/**
	 * Get the [author_url] column value.
	 * 
	 * @return     string
	 */
	public function getAuthorUrl()
	{
		return $this->author_url;
	}

	/**
	 * Get the [content] column value.
	 * 
	 * @return     string
	 */
	public function getContent()
	{
		return $this->content;
	}

	/**
	 * Get the [is_moderated] column value.
	 * 
	 * @return     boolean
	 */
	public function getIsModerated()
	{
		return $this->is_moderated;
	}

	/**
	 * Get the [commentable_model] column value.
	 * 
	 * @return     string
	 */
	public function getCommentableModel()
	{
		return $this->commentable_model;
	}

	/**
	 * Get the [commentable_id] column value.
	 * 
	 * @return     int
	 */
	public function getCommentableId()
	{
		return $this->commentable_id;
	}

	/**
	 * Get the [user_id] column value.
	 * 
	 * @return     int
	 */
	public function getUserId()
	{
		return $this->user_id;
	}

	/**
	 * Get the [sf_comment_id] column value.
	 * 
	 * @return     int
	 */
	public function getSfCommentId()
	{
		return $this->sf_comment_id;
	}

	/**
	 * Get the [extra] column value.
	 * 
	 * @return     string
	 */
	public function getExtra()
	{
		return $this->extra;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [tree_left] column value.
	 * 
	 * @return     int
	 */
	public function getTreeLeft()
	{
		return $this->tree_left;
	}

	/**
	 * Get the [tree_right] column value.
	 * 
	 * @return     int
	 */
	public function getTreeRight()
	{
		return $this->tree_right;
	}

	/**
	 * Get the [tree_level] column value.
	 * 
	 * @return     int
	 */
	public function getTreeLevel()
	{
		return $this->tree_level;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     sfNestedComment The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = sfNestedCommentPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [author_name] column.
	 * 
	 * @param      string $v new value
	 * @return     sfNestedComment The current object (for fluent API support)
	 */
	public function setAuthorName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->author_name !== $v) {
			$this->author_name = $v;
			$this->modifiedColumns[] = sfNestedCommentPeer::AUTHOR_NAME;
		}

		return $this;
	} // setAuthorName()

	/**
	 * Set the value of [author_email] column.
	 * 
	 * @param      string $v new value
	 * @return     sfNestedComment The current object (for fluent API support)
	 */
	public function setAuthorEmail($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->author_email !== $v) {
			$this->author_email = $v;
			$this->modifiedColumns[] = sfNestedCommentPeer::AUTHOR_EMAIL;
		}

		return $this;
	} // setAuthorEmail()

	/**
	 * Set the value of [author_url] column.
	 * 
	 * @param      string $v new value
	 * @return     sfNestedComment The current object (for fluent API support)
	 */
	public function setAuthorUrl($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->author_url !== $v) {
			$this->author_url = $v;
			$this->modifiedColumns[] = sfNestedCommentPeer::AUTHOR_URL;
		}

		return $this;
	} // setAuthorUrl()

	/**
	 * Set the value of [content] column.
	 * 
	 * @param      string $v new value
	 * @return     sfNestedComment The current object (for fluent API support)
	 */
	public function setContent($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->content !== $v) {
			$this->content = $v;
			$this->modifiedColumns[] = sfNestedCommentPeer::CONTENT;
		}

		return $this;
	} // setContent()

	/**
	 * Set the value of [is_moderated] column.
	 * 
	 * @param      boolean $v new value
	 * @return     sfNestedComment The current object (for fluent API support)
	 */
	public function setIsModerated($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->is_moderated !== $v || $this->isNew()) {
			$this->is_moderated = $v;
			$this->modifiedColumns[] = sfNestedCommentPeer::IS_MODERATED;
		}

		return $this;
	} // setIsModerated()

	/**
	 * Set the value of [commentable_model] column.
	 * 
	 * @param      string $v new value
	 * @return     sfNestedComment The current object (for fluent API support)
	 */
	public function setCommentableModel($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->commentable_model !== $v) {
			$this->commentable_model = $v;
			$this->modifiedColumns[] = sfNestedCommentPeer::COMMENTABLE_MODEL;
		}

		return $this;
	} // setCommentableModel()

	/**
	 * Set the value of [commentable_id] column.
	 * 
	 * @param      int $v new value
	 * @return     sfNestedComment The current object (for fluent API support)
	 */
	public function setCommentableId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->commentable_id !== $v) {
			$this->commentable_id = $v;
			$this->modifiedColumns[] = sfNestedCommentPeer::COMMENTABLE_ID;
		}

		return $this;
	} // setCommentableId()

	/**
	 * Set the value of [user_id] column.
	 * 
	 * @param      int $v new value
	 * @return     sfNestedComment The current object (for fluent API support)
	 */
	public function setUserId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->user_id !== $v) {
			$this->user_id = $v;
			$this->modifiedColumns[] = sfNestedCommentPeer::USER_ID;
		}

		return $this;
	} // setUserId()

	/**
	 * Set the value of [sf_comment_id] column.
	 * 
	 * @param      int $v new value
	 * @return     sfNestedComment The current object (for fluent API support)
	 */
	public function setSfCommentId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->sf_comment_id !== $v) {
			$this->sf_comment_id = $v;
			$this->modifiedColumns[] = sfNestedCommentPeer::SF_COMMENT_ID;
		}

		if ($this->asfNestedCommentRelatedBySfCommentId !== null && $this->asfNestedCommentRelatedBySfCommentId->getId() !== $v) {
			$this->asfNestedCommentRelatedBySfCommentId = null;
		}

		return $this;
	} // setSfCommentId()

	/**
	 * Set the value of [extra] column.
	 * 
	 * @param      string $v new value
	 * @return     sfNestedComment The current object (for fluent API support)
	 */
	public function setExtra($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra !== $v) {
			$this->extra = $v;
			$this->modifiedColumns[] = sfNestedCommentPeer::EXTRA;
		}

		return $this;
	} // setExtra()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     sfNestedComment The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = sfNestedCommentPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     sfNestedComment The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = sfNestedCommentPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Set the value of [tree_left] column.
	 * 
	 * @param      int $v new value
	 * @return     sfNestedComment The current object (for fluent API support)
	 */
	public function setTreeLeft($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->tree_left !== $v) {
			$this->tree_left = $v;
			$this->modifiedColumns[] = sfNestedCommentPeer::TREE_LEFT;
		}

		return $this;
	} // setTreeLeft()

	/**
	 * Set the value of [tree_right] column.
	 * 
	 * @param      int $v new value
	 * @return     sfNestedComment The current object (for fluent API support)
	 */
	public function setTreeRight($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->tree_right !== $v) {
			$this->tree_right = $v;
			$this->modifiedColumns[] = sfNestedCommentPeer::TREE_RIGHT;
		}

		return $this;
	} // setTreeRight()

	/**
	 * Set the value of [tree_level] column.
	 * 
	 * @param      int $v new value
	 * @return     sfNestedComment The current object (for fluent API support)
	 */
	public function setTreeLevel($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->tree_level !== $v) {
			$this->tree_level = $v;
			$this->modifiedColumns[] = sfNestedCommentPeer::TREE_LEVEL;
		}

		return $this;
	} // setTreeLevel()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->is_moderated !== false) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->author_name = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->author_email = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->author_url = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->content = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->is_moderated = ($row[$startcol + 5] !== null) ? (boolean) $row[$startcol + 5] : null;
			$this->commentable_model = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->commentable_id = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->user_id = ($row[$startcol + 8] !== null) ? (int) $row[$startcol + 8] : null;
			$this->sf_comment_id = ($row[$startcol + 9] !== null) ? (int) $row[$startcol + 9] : null;
			$this->extra = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->created_at = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->updated_at = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->tree_left = ($row[$startcol + 13] !== null) ? (int) $row[$startcol + 13] : null;
			$this->tree_right = ($row[$startcol + 14] !== null) ? (int) $row[$startcol + 14] : null;
			$this->tree_level = ($row[$startcol + 15] !== null) ? (int) $row[$startcol + 15] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			return $startcol + 16; // 16 = sfNestedCommentPeer::NUM_COLUMNS - sfNestedCommentPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating sfNestedComment object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->asfNestedCommentRelatedBySfCommentId !== null && $this->sf_comment_id !== $this->asfNestedCommentRelatedBySfCommentId->getId()) {
			$this->asfNestedCommentRelatedBySfCommentId = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(sfNestedCommentPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = sfNestedCommentPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->asfNestedCommentRelatedBySfCommentId = null;
			$this->collsfNestedCommentsRelatedById = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(sfNestedCommentPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// nested_set behavior
			if ($this->isRoot()) {
				throw new PropelException('Deletion of a root node is disabled for nested sets. Use sfNestedCommentPeer::deleteTree($scope) instead to delete an entire tree');
			}
			$this->deleteDescendants($con);

			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BasesfNestedComment:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			    return;
			  }
			}

			if ($ret) {
				sfNestedCommentQuery::create()
					->filterByPrimaryKey($this->getPrimaryKey())
					->delete($con);
				$this->postDelete($con);
				// nested_set behavior
				// fill up the room that was used by the node
				sfNestedCommentPeer::shiftRLValues(-2, $this->getRightValue() + 1, null, $this->getScopeValue(), $con);

				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BasesfNestedComment:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$con->commit();
				$this->setDeleted(true);
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(sfNestedCommentPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// nested_set behavior
			$this->processNestedSetQueries($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BasesfNestedComment:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			  	$con->commit();
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			if ($this->isModified() && !$this->isColumnModified(sfNestedCommentPeer::UPDATED_AT))
			{
			  $this->setUpdatedAt(time());
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(sfNestedCommentPeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BasesfNestedComment:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				sfNestedCommentPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->asfNestedCommentRelatedBySfCommentId !== null) {
				if ($this->asfNestedCommentRelatedBySfCommentId->isModified() || $this->asfNestedCommentRelatedBySfCommentId->isNew()) {
					$affectedRows += $this->asfNestedCommentRelatedBySfCommentId->save($con);
				}
				$this->setsfNestedCommentRelatedBySfCommentId($this->asfNestedCommentRelatedBySfCommentId);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = sfNestedCommentPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$criteria = $this->buildCriteria();
					if ($criteria->keyContainsValue(sfNestedCommentPeer::ID) ) {
						throw new PropelException('Cannot insert a value for auto-increment primary key ('.sfNestedCommentPeer::ID.')');
					}

					$pk = BasePeer::doInsert($criteria, $con);
					$affectedRows += 1;
					$this->setId($pk);  //[IMV] update autoincrement primary key
					$this->setNew(false);
				} else {
					$affectedRows += sfNestedCommentPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collsfNestedCommentsRelatedById !== null) {
				foreach ($this->collsfNestedCommentsRelatedById as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->asfNestedCommentRelatedBySfCommentId !== null) {
				if (!$this->asfNestedCommentRelatedBySfCommentId->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->asfNestedCommentRelatedBySfCommentId->getValidationFailures());
				}
			}


			if (($retval = sfNestedCommentPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collsfNestedCommentsRelatedById !== null) {
					foreach ($this->collsfNestedCommentsRelatedById as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = sfNestedCommentPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getAuthorName();
				break;
			case 2:
				return $this->getAuthorEmail();
				break;
			case 3:
				return $this->getAuthorUrl();
				break;
			case 4:
				return $this->getContent();
				break;
			case 5:
				return $this->getIsModerated();
				break;
			case 6:
				return $this->getCommentableModel();
				break;
			case 7:
				return $this->getCommentableId();
				break;
			case 8:
				return $this->getUserId();
				break;
			case 9:
				return $this->getSfCommentId();
				break;
			case 10:
				return $this->getExtra();
				break;
			case 11:
				return $this->getCreatedAt();
				break;
			case 12:
				return $this->getUpdatedAt();
				break;
			case 13:
				return $this->getTreeLeft();
				break;
			case 14:
				return $this->getTreeRight();
				break;
			case 15:
				return $this->getTreeLevel();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param     string  $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 *                    BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 *                    Defaults to BasePeer::TYPE_PHPNAME.
	 * @param     boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns. Defaults to TRUE.
	 * @param     boolean $includeForeignObjects (optional) Whether to include hydrated related objects. Default to FALSE.
	 *
	 * @return    array an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true, $includeForeignObjects = false)
	{
		$keys = sfNestedCommentPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getAuthorName(),
			$keys[2] => $this->getAuthorEmail(),
			$keys[3] => $this->getAuthorUrl(),
			$keys[4] => $this->getContent(),
			$keys[5] => $this->getIsModerated(),
			$keys[6] => $this->getCommentableModel(),
			$keys[7] => $this->getCommentableId(),
			$keys[8] => $this->getUserId(),
			$keys[9] => $this->getSfCommentId(),
			$keys[10] => $this->getExtra(),
			$keys[11] => $this->getCreatedAt(),
			$keys[12] => $this->getUpdatedAt(),
			$keys[13] => $this->getTreeLeft(),
			$keys[14] => $this->getTreeRight(),
			$keys[15] => $this->getTreeLevel(),
		);
		if ($includeForeignObjects) {
			if (null !== $this->asfNestedCommentRelatedBySfCommentId) {
				$result['sfNestedCommentRelatedBySfCommentId'] = $this->asfNestedCommentRelatedBySfCommentId->toArray($keyType, $includeLazyLoadColumns, true);
			}
		}
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = sfNestedCommentPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setAuthorName($value);
				break;
			case 2:
				$this->setAuthorEmail($value);
				break;
			case 3:
				$this->setAuthorUrl($value);
				break;
			case 4:
				$this->setContent($value);
				break;
			case 5:
				$this->setIsModerated($value);
				break;
			case 6:
				$this->setCommentableModel($value);
				break;
			case 7:
				$this->setCommentableId($value);
				break;
			case 8:
				$this->setUserId($value);
				break;
			case 9:
				$this->setSfCommentId($value);
				break;
			case 10:
				$this->setExtra($value);
				break;
			case 11:
				$this->setCreatedAt($value);
				break;
			case 12:
				$this->setUpdatedAt($value);
				break;
			case 13:
				$this->setTreeLeft($value);
				break;
			case 14:
				$this->setTreeRight($value);
				break;
			case 15:
				$this->setTreeLevel($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = sfNestedCommentPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setAuthorName($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setAuthorEmail($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setAuthorUrl($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setContent($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setIsModerated($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setCommentableModel($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setCommentableId($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setUserId($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setSfCommentId($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setExtra($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setCreatedAt($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setUpdatedAt($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setTreeLeft($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setTreeRight($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setTreeLevel($arr[$keys[15]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(sfNestedCommentPeer::DATABASE_NAME);

		if ($this->isColumnModified(sfNestedCommentPeer::ID)) $criteria->add(sfNestedCommentPeer::ID, $this->id);
		if ($this->isColumnModified(sfNestedCommentPeer::AUTHOR_NAME)) $criteria->add(sfNestedCommentPeer::AUTHOR_NAME, $this->author_name);
		if ($this->isColumnModified(sfNestedCommentPeer::AUTHOR_EMAIL)) $criteria->add(sfNestedCommentPeer::AUTHOR_EMAIL, $this->author_email);
		if ($this->isColumnModified(sfNestedCommentPeer::AUTHOR_URL)) $criteria->add(sfNestedCommentPeer::AUTHOR_URL, $this->author_url);
		if ($this->isColumnModified(sfNestedCommentPeer::CONTENT)) $criteria->add(sfNestedCommentPeer::CONTENT, $this->content);
		if ($this->isColumnModified(sfNestedCommentPeer::IS_MODERATED)) $criteria->add(sfNestedCommentPeer::IS_MODERATED, $this->is_moderated);
		if ($this->isColumnModified(sfNestedCommentPeer::COMMENTABLE_MODEL)) $criteria->add(sfNestedCommentPeer::COMMENTABLE_MODEL, $this->commentable_model);
		if ($this->isColumnModified(sfNestedCommentPeer::COMMENTABLE_ID)) $criteria->add(sfNestedCommentPeer::COMMENTABLE_ID, $this->commentable_id);
		if ($this->isColumnModified(sfNestedCommentPeer::USER_ID)) $criteria->add(sfNestedCommentPeer::USER_ID, $this->user_id);
		if ($this->isColumnModified(sfNestedCommentPeer::SF_COMMENT_ID)) $criteria->add(sfNestedCommentPeer::SF_COMMENT_ID, $this->sf_comment_id);
		if ($this->isColumnModified(sfNestedCommentPeer::EXTRA)) $criteria->add(sfNestedCommentPeer::EXTRA, $this->extra);
		if ($this->isColumnModified(sfNestedCommentPeer::CREATED_AT)) $criteria->add(sfNestedCommentPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(sfNestedCommentPeer::UPDATED_AT)) $criteria->add(sfNestedCommentPeer::UPDATED_AT, $this->updated_at);
		if ($this->isColumnModified(sfNestedCommentPeer::TREE_LEFT)) $criteria->add(sfNestedCommentPeer::TREE_LEFT, $this->tree_left);
		if ($this->isColumnModified(sfNestedCommentPeer::TREE_RIGHT)) $criteria->add(sfNestedCommentPeer::TREE_RIGHT, $this->tree_right);
		if ($this->isColumnModified(sfNestedCommentPeer::TREE_LEVEL)) $criteria->add(sfNestedCommentPeer::TREE_LEVEL, $this->tree_level);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(sfNestedCommentPeer::DATABASE_NAME);
		$criteria->add(sfNestedCommentPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Returns true if the primary key for this object is null.
	 * @return     boolean
	 */
	public function isPrimaryKeyNull()
	{
		return null === $this->getId();
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of sfNestedComment (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{
		$copyObj->setAuthorName($this->author_name);
		$copyObj->setAuthorEmail($this->author_email);
		$copyObj->setAuthorUrl($this->author_url);
		$copyObj->setContent($this->content);
		$copyObj->setIsModerated($this->is_moderated);
		$copyObj->setCommentableModel($this->commentable_model);
		$copyObj->setCommentableId($this->commentable_id);
		$copyObj->setUserId($this->user_id);
		$copyObj->setSfCommentId($this->sf_comment_id);
		$copyObj->setExtra($this->extra);
		$copyObj->setCreatedAt($this->created_at);
		$copyObj->setUpdatedAt($this->updated_at);
		$copyObj->setTreeLeft($this->tree_left);
		$copyObj->setTreeRight($this->tree_right);
		$copyObj->setTreeLevel($this->tree_level);

		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getsfNestedCommentsRelatedById() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addsfNestedCommentRelatedById($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);
		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value
	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     sfNestedComment Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     sfNestedCommentPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new sfNestedCommentPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a sfNestedComment object.
	 *
	 * @param      sfNestedComment $v
	 * @return     sfNestedComment The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setsfNestedCommentRelatedBySfCommentId(sfNestedComment $v = null)
	{
		if ($v === null) {
			$this->setSfCommentId(NULL);
		} else {
			$this->setSfCommentId($v->getId());
		}

		$this->asfNestedCommentRelatedBySfCommentId = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the sfNestedComment object, it will not be re-added.
		if ($v !== null) {
			$v->addsfNestedCommentRelatedById($this);
		}

		return $this;
	}


	/**
	 * Get the associated sfNestedComment object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     sfNestedComment The associated sfNestedComment object.
	 * @throws     PropelException
	 */
	public function getsfNestedCommentRelatedBySfCommentId(PropelPDO $con = null)
	{
		if ($this->asfNestedCommentRelatedBySfCommentId === null && ($this->sf_comment_id !== null)) {
			$this->asfNestedCommentRelatedBySfCommentId = sfNestedCommentQuery::create()->findPk($this->sf_comment_id, $con);
			/* The following can be used additionally to
				 guarantee the related object contains a reference
				 to this object.  This level of coupling may, however, be
				 undesirable since it could result in an only partially populated collection
				 in the referenced object.
				 $this->asfNestedCommentRelatedBySfCommentId->addsfNestedCommentsRelatedById($this);
			 */
		}
		return $this->asfNestedCommentRelatedBySfCommentId;
	}

	/**
	 * Clears out the collsfNestedCommentsRelatedById collection
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addsfNestedCommentsRelatedById()
	 */
	public function clearsfNestedCommentsRelatedById()
	{
		$this->collsfNestedCommentsRelatedById = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collsfNestedCommentsRelatedById collection.
	 *
	 * By default this just sets the collsfNestedCommentsRelatedById collection to an empty array (like clearcollsfNestedCommentsRelatedById());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initsfNestedCommentsRelatedById()
	{
		$this->collsfNestedCommentsRelatedById = new PropelObjectCollection();
		$this->collsfNestedCommentsRelatedById->setModel('sfNestedComment');
	}

	/**
	 * Gets an array of sfNestedComment objects which contain a foreign key that references this object.
	 *
	 * If the $criteria is not null, it is used to always fetch the results from the database.
	 * Otherwise the results are fetched from the database the first time, then cached.
	 * Next time the same method is called without $criteria, the cached collection is returned.
	 * If this sfNestedComment is new, it will return
	 * an empty collection or the current collection; the criteria is ignored on a new object.
	 *
	 * @param      Criteria $criteria optional Criteria object to narrow the query
	 * @param      PropelPDO $con optional connection object
	 * @return     PropelCollection|array sfNestedComment[] List of sfNestedComment objects
	 * @throws     PropelException
	 */
	public function getsfNestedCommentsRelatedById($criteria = null, PropelPDO $con = null)
	{
		if(null === $this->collsfNestedCommentsRelatedById || null !== $criteria) {
			if ($this->isNew() && null === $this->collsfNestedCommentsRelatedById) {
				// return empty collection
				$this->initsfNestedCommentsRelatedById();
			} else {
				$collsfNestedCommentsRelatedById = sfNestedCommentQuery::create(null, $criteria)
					->filterBysfNestedCommentRelatedBySfCommentId($this)
					->find($con);
				if (null !== $criteria) {
					return $collsfNestedCommentsRelatedById;
				}
				$this->collsfNestedCommentsRelatedById = $collsfNestedCommentsRelatedById;
			}
		}
		return $this->collsfNestedCommentsRelatedById;
	}

	/**
	 * Returns the number of related sfNestedComment objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related sfNestedComment objects.
	 * @throws     PropelException
	 */
	public function countsfNestedCommentsRelatedById(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if(null === $this->collsfNestedCommentsRelatedById || null !== $criteria) {
			if ($this->isNew() && null === $this->collsfNestedCommentsRelatedById) {
				return 0;
			} else {
				$query = sfNestedCommentQuery::create(null, $criteria);
				if($distinct) {
					$query->distinct();
				}
				return $query
					->filterBysfNestedCommentRelatedBySfCommentId($this)
					->count($con);
			}
		} else {
			return count($this->collsfNestedCommentsRelatedById);
		}
	}

	/**
	 * Method called to associate a sfNestedComment object to this object
	 * through the sfNestedComment foreign key attribute.
	 *
	 * @param      sfNestedComment $l sfNestedComment
	 * @return     void
	 * @throws     PropelException
	 */
	public function addsfNestedCommentRelatedById(sfNestedComment $l)
	{
		if ($this->collsfNestedCommentsRelatedById === null) {
			$this->initsfNestedCommentsRelatedById();
		}
		if (!$this->collsfNestedCommentsRelatedById->contains($l)) { // only add it if the **same** object is not already associated
			$this->collsfNestedCommentsRelatedById[]= $l;
			$l->setsfNestedCommentRelatedBySfCommentId($this);
		}
	}

	/**
	 * Clears the current object and sets all attributes to their default values
	 */
	public function clear()
	{
		$this->id = null;
		$this->author_name = null;
		$this->author_email = null;
		$this->author_url = null;
		$this->content = null;
		$this->is_moderated = null;
		$this->commentable_model = null;
		$this->commentable_id = null;
		$this->user_id = null;
		$this->sf_comment_id = null;
		$this->extra = null;
		$this->created_at = null;
		$this->updated_at = null;
		$this->tree_left = null;
		$this->tree_right = null;
		$this->tree_level = null;
		$this->alreadyInSave = false;
		$this->alreadyInValidation = false;
		$this->clearAllReferences();
		$this->applyDefaultValues();
		$this->resetModified();
		$this->setNew(true);
		$this->setDeleted(false);
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collsfNestedCommentsRelatedById) {
				foreach ((array) $this->collsfNestedCommentsRelatedById as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		// nested_set behavior
		$this->collNestedSetChildren = null;
		$this->aNestedSetParent = null;
		$this->collsfNestedCommentsRelatedById = null;
		$this->asfNestedCommentRelatedBySfCommentId = null;
	}

	// nested_set behavior
	
	/**
	 * Execute queries that were saved to be run inside the save transaction
	 */
	protected function processNestedSetQueries($con)
	{
		foreach ($this->nestedSetQueries as $query) {
			$query['arguments'][]= $con;
			call_user_func_array($query['callable'], $query['arguments']);
		}
		$this->nestedSetQueries = array();
	}
	
	/**
	 * Wraps the getter for the nested set left value
	 *
	 * @return     int
	 */
	public function getLeftValue()
	{
		return $this->tree_left;
	}
	
	/**
	 * Wraps the getter for the nested set right value
	 *
	 * @return     int
	 */
	public function getRightValue()
	{
		return $this->tree_right;
	}
	
	/**
	 * Wraps the getter for the nested set level
	 *
	 * @return     int
	 */
	public function getLevel()
	{
		return $this->tree_level;
	}
	
	/**
	 * Wraps the getter for the scope value
	 *
	 * @return     int or null if scope is disabled
	 */
	public function getScopeValue()
	{
		return $this->extra;
	}
	
	/**
	 * Set the value left column
	 *
	 * @param      int $v new value
	 * @return     sfNestedComment The current object (for fluent API support)
	 */
	public function setLeftValue($v)
	{
		return $this->setTreeLeft($v);
	}
	
	/**
	 * Set the value of right column
	 *
	 * @param      int $v new value
	 * @return     sfNestedComment The current object (for fluent API support)
	 */
	public function setRightValue($v)
	{
		return $this->setTreeRight($v);
	}
	
	/**
	 * Set the value of level column
	 *
	 * @param      int $v new value
	 * @return     sfNestedComment The current object (for fluent API support)
	 */
	public function setLevel($v)
	{
		return $this->setTreeLevel($v);
	}
	
	/**
	 * Set the value of scope column
	 *
	 * @param      int $v new value
	 * @return     sfNestedComment The current object (for fluent API support)
	 */
	public function setScopeValue($v)
	{
		return $this->setExtra($v);
	}
	
	/**
	 * Creates the supplied node as the root node.
	 *
	 * @return     sfNestedComment The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function makeRoot()
	{
		if ($this->getLeftValue() || $this->getRightValue()) {
			throw new PropelException('Cannot turn an existing node into a root node.');
		}
	
		$this->setLeftValue(1);
		$this->setRightValue(2);
		$this->setLevel(0);
		return $this;
	}
	
	/**
	 * Tests if onbject is a node, i.e. if it is inserted in the tree
	 *
	 * @return     bool
	 */
	public function isInTree()
	{
		return $this->getLeftValue() > 0 && $this->getRightValue() > $this->getLeftValue();
	}
	
	/**
	 * Tests if node is a root
	 *
	 * @return     bool
	 */
	public function isRoot()
	{
		return $this->isInTree() && $this->getLeftValue() == 1;
	}
	
	/**
	 * Tests if node is a leaf
	 *
	 * @return     bool
	 */
	public function isLeaf()
	{
		return $this->isInTree() &&  ($this->getRightValue() - $this->getLeftValue()) == 1;
	}
	
	/**
	 * Tests if node is a descendant of another node
	 *
	 * @param      sfNestedComment $node Propel node object
	 * @return     bool
	 */
	public function isDescendantOf($parent)
	{
		if ($this->getScopeValue() !== $parent->getScopeValue()) {
			throw new PropelException('Comparing two nodes of different trees');
		}
		return $this->isInTree() && $this->getLeftValue() > $parent->getLeftValue() && $this->getRightValue() < $parent->getRightValue();
	}
	
	/**
	 * Tests if node is a ancestor of another node
	 *
	 * @param      sfNestedComment $node Propel node object
	 * @return     bool
	 */
	public function isAncestorOf($child)
	{
		return $child->isDescendantOf($this);
	}
	
	/**
	 * Tests if object has an ancestor
	 *
	 * @param      PropelPDO $con Connection to use.
	 * @return     bool
	 */
	public function hasParent(PropelPDO $con = null)
	{
		return $this->getLevel() > 0;
	}
	
	/**
	 * Sets the cache for parent node of the current object.
	 * Warning: this does not move the current object in the tree.
	 * Use moveTofirstChildOf() or moveToLastChildOf() for that purpose
	 *
	 * @param      sfNestedComment $parent
	 * @return     sfNestedComment The current object, for fluid interface
	 */
	public function setParent($parent = null)
	{
		$this->aNestedSetParent = $parent;
		return $this;
	}
	
	/**
	 * Gets parent node for the current object if it exists
	 * The result is cached so further calls to the same method don't issue any queries
	 *
	 * @param      PropelPDO $con Connection to use.
	 * @return     mixed 		Propel object if exists else false
	 */
	public function getParent(PropelPDO $con = null)
	{
		if ($this->aNestedSetParent === null && $this->hasParent()) {
			$this->aNestedSetParent = sfNestedCommentQuery::create()
				->ancestorsOf($this)
				->orderByLevel(true)
				->findOne($con);
		}
		return $this->aNestedSetParent;
	}
	
	/**
	 * Determines if the node has previous sibling
	 *
	 * @param      PropelPDO $con Connection to use.
	 * @return     bool
	 */
	public function hasPrevSibling(PropelPDO $con = null)
	{
		if (!sfNestedCommentPeer::isValid($this)) {
			return false;
		}
		return sfNestedCommentQuery::create()
			->filterByTreeRight($this->getLeftValue() - 1)
			->inTree($this->getScopeValue())
			->count($con) > 0;
	}
	
	/**
	 * Gets previous sibling for the given node if it exists
	 *
	 * @param      PropelPDO $con Connection to use.
	 * @return     mixed 		Propel object if exists else false
	 */
	public function getPrevSibling(PropelPDO $con = null)
	{
		return sfNestedCommentQuery::create()
			->filterByTreeRight($this->getLeftValue() - 1)
			->inTree($this->getScopeValue())
			->findOne($con);
	}
	
	/**
	 * Determines if the node has next sibling
	 *
	 * @param      PropelPDO $con Connection to use.
	 * @return     bool
	 */
	public function hasNextSibling(PropelPDO $con = null)
	{
		if (!sfNestedCommentPeer::isValid($this)) {
			return false;
		}
		return sfNestedCommentQuery::create()
			->filterByTreeLeft($this->getRightValue() + 1)
			->inTree($this->getScopeValue())
			->count($con) > 0;
	}
	
	/**
	 * Gets next sibling for the given node if it exists
	 *
	 * @param      PropelPDO $con Connection to use.
	 * @return     mixed 		Propel object if exists else false
	 */
	public function getNextSibling(PropelPDO $con = null)
	{
		return sfNestedCommentQuery::create()
			->filterByTreeLeft($this->getRightValue() + 1)
			->inTree($this->getScopeValue())
			->findOne($con);
	}
	
	/**
	 * Clears out the $collNestedSetChildren collection
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 */
	public function clearNestedSetChildren()
	{
		$this->collNestedSetChildren = null;
	}
	
	/**
	 * Initializes the $collNestedSetChildren collection.
	 *
	 * @return     void
	 */
	public function initNestedSetChildren()
	{
		$this->collNestedSetChildren = new PropelObjectCollection();
		$this->collNestedSetChildren->setModel('sfNestedComment');
	}
	
	/**
	 * Adds an element to the internal $collNestedSetChildren collection.
	 * Beware that this doesn't insert a node in the tree.
	 * This method is only used to facilitate children hydration.
	 *
	 * @param      sfNestedComment $sfNestedComment
	 *
	 * @return     void
	 */
	public function addNestedSetChild($sfNestedComment)
	{
		if ($this->collNestedSetChildren === null) {
			$this->initNestedSetChildren();
		}
		if (!$this->collNestedSetChildren->contains($sfNestedComment)) { // only add it if the **same** object is not already associated
			$this->collNestedSetChildren[]= $sfNestedComment;
			$sfNestedComment->setParent($this);
		}
	}
	
	/**
	 * Tests if node has children
	 *
	 * @return     bool
	 */
	public function hasChildren()
	{
		return ($this->getRightValue() - $this->getLeftValue()) > 1;
	}
	
	/**
	 * Gets the children of the given node
	 *
	 * @param      Criteria  $criteria Criteria to filter results.
	 * @param      PropelPDO $con Connection to use.
	 * @return     array     List of sfNestedComment objects
	 */
	public function getChildren($criteria = null, PropelPDO $con = null)
	{
		if(null === $this->collNestedSetChildren || null !== $criteria) {
			if ($this->isLeaf() || ($this->isNew() && null === $this->collNestedSetChildren)) {
				// return empty collection
				$this->initNestedSetChildren();
			} else {
				$collNestedSetChildren = sfNestedCommentQuery::create(null, $criteria)
	  			->childrenOf($this)
	  			->orderByBranch()
					->find($con);
				if (null !== $criteria) {
					return $collNestedSetChildren;
				}
				$this->collNestedSetChildren = $collNestedSetChildren;
			}
		}
		return $this->collNestedSetChildren;
	}
	
	/**
	 * Gets number of children for the given node
	 *
	 * @param      Criteria  $criteria Criteria to filter results. 
	 * @param      PropelPDO $con Connection to use.
	 * @return     int       Number of children
	 */
	public function countChildren($criteria = null, PropelPDO $con = null)
	{
		if(null === $this->collNestedSetChildren || null !== $criteria) {
			if ($this->isLeaf() || ($this->isNew() && null === $this->collNestedSetChildren)) {
				return 0;
			} else {
				return sfNestedCommentQuery::create(null, $criteria)
					->childrenOf($this)
					->count($con);
			}
		} else {
			return count($this->collNestedSetChildren);
		}
	}
	
	/**
	 * Gets the first child of the given node
	 *
	 * @param      Criteria $query Criteria to filter results. 
	 * @param      PropelPDO $con Connection to use.
	 * @return     array 		List of sfNestedComment objects
	 */
	public function getFirstChild($query = null, PropelPDO $con = null)
	{
		if($this->isLeaf()) {
			return array();
		} else {
			return sfNestedCommentQuery::create(null, $query)
				->childrenOf($this)
				->orderByBranch()
				->findOne($con);
		}
	}
	
	/**
	 * Gets the last child of the given node
	 *
	 * @param      Criteria $query Criteria to filter results. 
	 * @param      PropelPDO $con Connection to use.
	 * @return     array 		List of sfNestedComment objects
	 */
	public function getLastChild($query = null, PropelPDO $con = null)
	{
		if($this->isLeaf()) {
			return array();
		} else {
			return sfNestedCommentQuery::create(null, $query)
				->childrenOf($this)
				->orderByBranch(true)
				->findOne($con);
		}
	}
	
	/**
	 * Gets the siblings of the given node
	 *
	 * @param      bool			$includeNode Whether to include the current node or not
	 * @param      Criteria $query Criteria to filter results. 
	 * @param      PropelPDO $con Connection to use.
	 *
	 * @return     array 		List of sfNestedComment objects
	 */
	public function getSiblings($includeNode = false, $query = null, PropelPDO $con = null)
	{
		if($this->isRoot()) {
			return array();
		} else {
			 $query = sfNestedCommentQuery::create(null, $query)
					->childrenOf($this->getParent($con))
					->orderByBranch();
			if (!$includeNode) {
				$query->prune($this);
			}
			return $query->find($con);
		}
	}
	
	/**
	 * Gets descendants for the given node
	 *
	 * @param      Criteria $query Criteria to filter results. 
	 * @param      PropelPDO $con Connection to use.
	 * @return     array 		List of sfNestedComment objects
	 */
	public function getDescendants($query = null, PropelPDO $con = null)
	{
		if($this->isLeaf()) {
			return array();
		} else {
			return sfNestedCommentQuery::create(null, $query)
				->descendantsOf($this)
				->orderByBranch()
				->find($con);
		}
	}
	
	/**
	 * Gets number of descendants for the given node
	 *
	 * @param      Criteria $query Criteria to filter results. 
	 * @param      PropelPDO $con Connection to use.
	 * @return     int 		Number of descendants
	 */
	public function countDescendants($query = null, PropelPDO $con = null)
	{
		if($this->isLeaf()) {
			// save one query
			return 0;
		} else {
			return sfNestedCommentQuery::create(null, $query)
				->descendantsOf($this)
				->count($con);
		}
	}
	
	/**
	 * Gets descendants for the given node, plus the current node
	 *
	 * @param      Criteria $query Criteria to filter results. 
	 * @param      PropelPDO $con Connection to use.
	 * @return     array 		List of sfNestedComment objects
	 */
	public function getBranch($query = null, PropelPDO $con = null)
	{
		return sfNestedCommentQuery::create(null, $query)
			->branchOf($this)
			->orderByBranch()
			->find($con);
	}
	
	/**
	 * Gets ancestors for the given node, starting with the root node
	 * Use it for breadcrumb paths for instance
	 *
	 * @param      Criteria $query Criteria to filter results. 
	 * @param      PropelPDO $con Connection to use.
	 * @return     array 		List of sfNestedComment objects
	 */
	public function getAncestors($query = null, PropelPDO $con = null)
	{
		if($this->isRoot()) {
			// save one query
			return array();
		} else {
			return sfNestedCommentQuery::create(null, $query)
				->ancestorsOf($this)
				->orderByBranch()
				->find($con);
		}
	}
	
	/**
	 * Inserts the given $child node as first child of current
	 * The modifications in the current object and the tree
	 * are not persisted until the child object is saved.
	 *
	 * @param      sfNestedComment $child	Propel object for child node
	 *
	 * @return     sfNestedComment The current Propel object
	 */
	public function addChild(sfNestedComment $child)
	{
		if ($this->isNew()) {
			throw new PropelException('A sfNestedComment object must not be new to accept children.');
		}
		$child->insertAsFirstChildOf($this);
		return $this;
	}
	
	/**
	 * Inserts the current node as first child of given $parent node
	 * The modifications in the current object and the tree
	 * are not persisted until the current object is saved.
	 *
	 * @param      sfNestedComment $parent	Propel object for parent node
	 *
	 * @return     sfNestedComment The current Propel object
	 */
	public function insertAsFirstChildOf($parent)
	{
		if ($this->isInTree()) {
			throw new PropelException('A sfNestedComment object must not already be in the tree to be inserted. Use the moveToFirstChildOf() instead.');
		}
		$left = $parent->getLeftValue() + 1;
		// Update node properties
		$this->setLeftValue($left);
		$this->setRightValue($left + 1);
		$this->setLevel($parent->getLevel() + 1);
		$scope = $parent->getScopeValue();
		$this->setScopeValue($scope);
		// update the children collection of the parent
		$parent->addNestedSetChild($this);
		
		// Keep the tree modification query for the save() transaction
		$this->nestedSetQueries []= array(
			'callable'  => array('sfNestedCommentPeer', 'makeRoomForLeaf'),
			'arguments' => array($left, $scope)
		);
		return $this;
	}
	
	/**
	 * Inserts the current node as last child of given $parent node
	 * The modifications in the current object and the tree
	 * are not persisted until the current object is saved.
	 *
	 * @param      sfNestedComment $parent	Propel object for parent node
	 *
	 * @return     sfNestedComment The current Propel object
	 */
	public function insertAsLastChildOf($parent)
	{
		if ($this->isInTree()) {
			throw new PropelException('A sfNestedComment object must not already be in the tree to be inserted. Use the moveToLastChildOf() instead.');
		}
		$left = $parent->getRightValue();
		// Update node properties
		$this->setLeftValue($left);
		$this->setRightValue($left + 1);
		$this->setLevel($parent->getLevel() + 1);
		$scope = $parent->getScopeValue();
		$this->setScopeValue($scope);
		// update the children collection of the parent
		$parent->addNestedSetChild($this);
		
		// Keep the tree modification query for the save() transaction
		$this->nestedSetQueries []= array(
			'callable'  => array('sfNestedCommentPeer', 'makeRoomForLeaf'),
			'arguments' => array($left, $scope)
		);
		return $this;
	}
	
	/**
	 * Inserts the current node as prev sibling given $sibling node
	 * The modifications in the current object and the tree
	 * are not persisted until the current object is saved.
	 *
	 * @param      sfNestedComment $sibling	Propel object for parent node
	 *
	 * @return     sfNestedComment The current Propel object
	 */
	public function insertAsPrevSiblingOf($sibling)
	{
		if ($this->isInTree()) {
			throw new PropelException('A sfNestedComment object must not already be in the tree to be inserted. Use the moveToPrevSiblingOf() instead.');
		}
		$left = $sibling->getLeftValue();
		// Update node properties
		$this->setLeftValue($left);
		$this->setRightValue($left + 1);
		$this->setLevel($sibling->getLevel());
		$scope = $sibling->getScopeValue();
		$this->setScopeValue($scope);
		// Keep the tree modification query for the save() transaction
		$this->nestedSetQueries []= array(
			'callable'  => array('sfNestedCommentPeer', 'makeRoomForLeaf'),
			'arguments' => array($left, $scope)
		);
		return $this;
	}
	
	/**
	 * Inserts the current node as next sibling given $sibling node
	 * The modifications in the current object and the tree
	 * are not persisted until the current object is saved.
	 *
	 * @param      sfNestedComment $sibling	Propel object for parent node
	 *
	 * @return     sfNestedComment The current Propel object
	 */
	public function insertAsNextSiblingOf($sibling)
	{
		if ($this->isInTree()) {
			throw new PropelException('A sfNestedComment object must not already be in the tree to be inserted. Use the moveToNextSiblingOf() instead.');
		}
		$left = $sibling->getRightValue() + 1;
		// Update node properties
		$this->setLeftValue($left);
		$this->setRightValue($left + 1);
		$this->setLevel($sibling->getLevel());
		$scope = $sibling->getScopeValue();
		$this->setScopeValue($scope);
		// Keep the tree modification query for the save() transaction
		$this->nestedSetQueries []= array(
			'callable'  => array('sfNestedCommentPeer', 'makeRoomForLeaf'),
			'arguments' => array($left, $scope)
		);
		return $this;
	}
	
	/**
	 * Moves current node and its subtree to be the first child of $parent
	 * The modifications in the current object and the tree are immediate
	 *
	 * @param      sfNestedComment $parent	Propel object for parent node
	 * @param      PropelPDO $con	Connection to use.
	 *
	 * @return     sfNestedComment The current Propel object
	 */
	public function moveToFirstChildOf($parent, PropelPDO $con = null)
	{
		if (!$this->isInTree()) {
			throw new PropelException('A sfNestedComment object must be already in the tree to be moved. Use the insertAsFirstChildOf() instead.');
		}
		if ($parent->getScopeValue() != $this->getScopeValue()) {
			throw new PropelException('Moving nodes across trees is not supported');
		}
		if ($parent->isDescendantOf($this)) {
			throw new PropelException('Cannot move a node as child of one of its subtree nodes.');
		}
		
		$this->moveSubtreeTo($parent->getLeftValue() + 1, $parent->getLevel() - $this->getLevel() + 1, $con);
		
		return $this;
	}
	
	/**
	 * Moves current node and its subtree to be the last child of $parent
	 * The modifications in the current object and the tree are immediate
	 *
	 * @param      sfNestedComment $parent	Propel object for parent node
	 * @param      PropelPDO $con	Connection to use.
	 *
	 * @return     sfNestedComment The current Propel object
	 */
	public function moveToLastChildOf($parent, PropelPDO $con = null)
	{
		if (!$this->isInTree()) {
			throw new PropelException('A sfNestedComment object must be already in the tree to be moved. Use the insertAsLastChildOf() instead.');
		}
		if ($parent->getScopeValue() != $this->getScopeValue()) {
			throw new PropelException('Moving nodes across trees is not supported');
		}
		if ($parent->isDescendantOf($this)) {
			throw new PropelException('Cannot move a node as child of one of its subtree nodes.');
		}
		
		$this->moveSubtreeTo($parent->getRightValue(), $parent->getLevel() - $this->getLevel() + 1, $con);
		
		return $this;
	}
	
	/**
	 * Moves current node and its subtree to be the previous sibling of $sibling
	 * The modifications in the current object and the tree are immediate
	 *
	 * @param      sfNestedComment $sibling	Propel object for sibling node
	 * @param      PropelPDO $con	Connection to use.
	 *
	 * @return     sfNestedComment The current Propel object
	 */
	public function moveToPrevSiblingOf($sibling, PropelPDO $con = null)
	{
		if (!$this->isInTree()) {
			throw new PropelException('A sfNestedComment object must be already in the tree to be moved. Use the insertAsPrevSiblingOf() instead.');
		}
		if ($sibling->isRoot()) {
			throw new PropelException('Cannot move to previous sibling of a root node.');
		}
		if ($sibling->getScopeValue() != $this->getScopeValue()) {
			throw new PropelException('Moving nodes across trees is not supported');
		}
		if ($sibling->isDescendantOf($this)) {
			throw new PropelException('Cannot move a node as sibling of one of its subtree nodes.');
		}
		
		$this->moveSubtreeTo($sibling->getLeftValue(), $sibling->getLevel() - $this->getLevel(), $con);
		
		return $this;
	}
	
	/**
	 * Moves current node and its subtree to be the next sibling of $sibling
	 * The modifications in the current object and the tree are immediate
	 *
	 * @param      sfNestedComment $sibling	Propel object for sibling node
	 * @param      PropelPDO $con	Connection to use.
	 *
	 * @return     sfNestedComment The current Propel object
	 */
	public function moveToNextSiblingOf($sibling, PropelPDO $con = null)
	{
		if (!$this->isInTree()) {
			throw new PropelException('A sfNestedComment object must be already in the tree to be moved. Use the insertAsNextSiblingOf() instead.');
		}
		if ($sibling->isRoot()) {
			throw new PropelException('Cannot move to next sibling of a root node.');
		}
		if ($sibling->getScopeValue() != $this->getScopeValue()) {
			throw new PropelException('Moving nodes across trees is not supported');
		}
		if ($sibling->isDescendantOf($this)) {
			throw new PropelException('Cannot move a node as sibling of one of its subtree nodes.');
		}
		
		$this->moveSubtreeTo($sibling->getRightValue() + 1, $sibling->getLevel() - $this->getLevel(), $con);
		
		return $this;
	}
	
	/**
	 * Move current node and its children to location $destLeft and updates rest of tree
	 *
	 * @param      int	$destLeft Destination left value
	 * @param      int	$levelDelta Delta to add to the levels
	 * @param      PropelPDO $con		Connection to use.
	 */
	protected function moveSubtreeTo($destLeft, $levelDelta, PropelPDO $con = null)
	{
		$left  = $this->getLeftValue();
		$right = $this->getRightValue();
		$scope = $this->getScopeValue();
	
		$treeSize = $right - $left +1;
		
		if ($con === null) {
			$con = Propel::getConnection(sfNestedCommentPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
			
		$con->beginTransaction();
		try {
			// make room next to the target for the subtree
			sfNestedCommentPeer::shiftRLValues($treeSize, $destLeft, null, $scope, $con);
		
			if ($left >= $destLeft) { // src was shifted too?
				$left += $treeSize;
				$right += $treeSize;
			}
			
			if ($levelDelta) {
				// update the levels of the subtree
				sfNestedCommentPeer::shiftLevel($levelDelta, $left, $right, $scope, $con);
			}
			
			// move the subtree to the target
			sfNestedCommentPeer::shiftRLValues($destLeft - $left, $left, $right, $scope, $con);
		
			// remove the empty room at the previous location of the subtree
			sfNestedCommentPeer::shiftRLValues(-$treeSize, $right + 1, null, $scope, $con);
			
			// update all loaded nodes
			sfNestedCommentPeer::updateLoadedNodes($con);
			
			$con->commit();
		} catch (PropelException $e) {
			$con->rollback();
			throw $e;
		}
	}
	
	/**
	 * Deletes all descendants for the given node
	 * Instance pooling is wiped out by this command, 
	 * so existing sfNestedComment instances are probably invalid (except for the current one)
	 *
	 * @param      PropelPDO $con Connection to use.
	 *
	 * @return     int 		number of deleted nodes
	 */
	public function deleteDescendants(PropelPDO $con = null)
	{
		if($this->isLeaf()) {
			// save one query
			return;
		}
		if ($con === null) {
			$con = Propel::getConnection(sfNestedCommentPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		$left = $this->getLeftValue();
		$right = $this->getRightValue();
		$scope = $this->getScopeValue();
		$con->beginTransaction();
		try {
			// delete descendant nodes (will empty the instance pool)
			$ret = sfNestedCommentQuery::create()
				->descendantsOf($this)
				->delete($con);
			
			// fill up the room that was used by descendants
			sfNestedCommentPeer::shiftRLValues($left - $right + 1, $right, null, $scope, $con);
			
			// fix the right value for the current node, which is now a leaf
			$this->setRightValue($left + 1);
			
			$con->commit();
		} catch (Exception $e) {
			$con->rollback();
			throw $e;
		}
		
		return $ret;
	}
	
	/**
	 * Returns a pre-order iterator for this node and its children.
	 *
	 * @return     RecursiveIterator
	 */
	public function getIterator()
	{
		return new NestedSetRecursiveIterator($this);
	}

	/**
	 * Catches calls to virtual methods
	 */
	public function __call($name, $params)
	{
		// symfony_behaviors behavior
		if ($callable = sfMixer::getCallable('BasesfNestedComment:' . $name))
		{
		  array_unshift($params, $this);
		  return call_user_func_array($callable, $params);
		}

		if (preg_match('/get(\w+)/', $name, $matches)) {
			$virtualColumn = $matches[1];
			if ($this->hasVirtualColumn($virtualColumn)) {
				return $this->getVirtualColumn($virtualColumn);
			}
			// no lcfirst in php<5.3...
			$virtualColumn[0] = strtolower($virtualColumn[0]);
			if ($this->hasVirtualColumn($virtualColumn)) {
				return $this->getVirtualColumn($virtualColumn);
			}
		}
		return parent::__call($name, $params);
	}

} // BasesfNestedComment
