<?php



/**
 * Skeleton subclass for performing query and update operations on the 'sf_nested_comment' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.5 on:
 *
 * Mon 03 Jan 2011 03:34:11 PM WIT
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfNestedCommentsPlugin.lib.model
 */
class sfNestedCommentPeer extends PluginsfNestedCommentPeer {

} // sfNestedCommentPeer
