<?php



/**
 * Skeleton subclass for performing query and update operations on the 'sf_nested_comment_mail_queue' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.0-dev on:
 *
 * Wed 30 Mar 2011 07:14:43 PM WIT
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfNestedCommentPlugin.lib.model
 */
class sfNestedCommentMailQueueQuery extends PluginsfNestedCommentMailQueueQuery {
  
} // sfNestedCommentMailQueueQuery
