<?php



/**
 * Skeleton subclass for representing a row from the 'sf_nested_comment' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.5 on:
 *
 * Mon 03 Jan 2011 03:34:11 PM WIT
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfNestedCommentsPlugin.lib.model
 */
class sfNestedComment extends PluginsfNestedComment {
  public function save(PropelPDO $con = null)
  {
    $parentComment = null;
    if ($this->getUserId() && $this->isNew())
    {
      $this->setIsModerated(false);
      if (null !== $parentId = $this->getSfCommentId())
      {
        $parentComment = sfNestedCommentQuery::create()->findPk($parentId);
        $parentComment->setIsModerated(false);
      }
    }
    $con = propel::getConnection();
    try
    {
      $con->beginTransaction();
      if (null !== $parentComment) $parentComment->save($con);
      $ret = parent::save($con);
      $con->commit();
      return $ret;
    }
    catch (Exception $e)
    {
      $con->rollBack();
      throw $e;
    }
  }
} // sfNestedComment
