<?php



/**
 * Skeleton subclass for representing a row from the 'sf_nested_comment_model' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.5 on:
 *
 * Wed 19 Jan 2011 10:56:39 PM WIT
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfNestedCommentPlugin.lib.model
 */
class sfNestedCommentableModel extends PluginsfNestedCommentableModel {

} // sfNestedCommentModel
